# Generated by Django 4.1.3 on 2022-11-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trading_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('minimum', models.CharField(max_length=100, null=True)),
                ('maximum', models.CharField(max_length=100, null=True)),
                ('daily_profit', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('withdraw_type', models.CharField(max_length=100, null=True)),
                ('ref', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'trading_plan',
            },
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=500, null=True, unique=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdraw',
            },
        ),
        migrations.CreateModel(
            name='tradings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('daily_profit', models.CharField(max_length=100, null=True)),
                ('net_profit', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('active_days', models.CharField(max_length=100, null=True)),
                ('next_day', models.CharField(max_length=100, null=True)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(max_length=100, null=True)),
                ('withdraw_type', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tradings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default=0, max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('user_type', models.IntegerField(default=0, null=True)),
                ('verification_code', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(max_length=500, null=True, unique=True)),
                ('reference_id', models.CharField(max_length=500, null=True, unique=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('method', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deposit',
            },
        ),
    ]
