# Generated by Django 4.1.3 on 2022-11-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradings',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='tradings',
            name='trading_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.trading_plan'),
        ),
    ]
