# Generated by Django 4.1.3 on 2022-11-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='full_name',
            new_name='account_name',
        ),
    ]
