# Generated by Django 4.1.3 on 2022-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_bank_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
