# Generated by Django 4.1.3 on 2022-11-23 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_bank_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField()),
                ('tradings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tradings')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
