# Generated by Django 4.1.3 on 2022-11-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_earnings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='earnings',
            table='earnings',
        ),
    ]
